### ISSUE TITLE
Using your plugin breaks asciidoctor

### ISSUE THREAD

**Issue by lairdchris** [codecholeric/gradle-plantuml-plugin#1]
Hi,
first, thanks for your plugin, exactly what I was looking for :-)
I wanted to use it in a documentation project where I'm using asciidoc to create a PDF and independend diagrams with plantuml.

My problem:
using your plugin in my build.gradle breaks usage of the asciidoctor gradle plugin. If I comment your lines, it works as expected.

build.gradle:
```
buildscript {
    dependencies {
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16',
            'org.asciidoctor:asciidoctorj-diagram:1.5.12'
      }
}

plugins {
    id "de.gafertp.plantuml" version "1.1.0"
    id 'org.asciidoctor.convert' version '1.5.9.1'
}

apply plugin: 'java'

asciidoctor {
    sourceDir = file('src/docs/asciidoc')
    outputDir = file("$buildDir")
    sources {
        include 'architecture.adoc'
    }

    attributes \
        'imagesDir': './images',
        'imagesOutDir': './images',
        'plantUMLDir': './plantuml/'

    backends 'pdf'
    requires 'asciidoctor-diagram'
}

plantUml {
    render input: 'src/docs/plantuml/*.pu', output: 'build/plantuml/', format: 'png'
}
```

running `gradle asciidoc` results in an exception:
```
Exception in thread "main" org.asciidoctor.gradle.backported.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process...
...
Caused by: java.lang.NoSuchMethodError: net.sourceforge.plantuml.Option.setFileFormatOption(Lnet/sourceforge/plantuml/FileFormatOption;)V
```

This seems to happen because of plantuml-8059.jar being downloaded as dependency. If I exchange the jar in my local repository with a newer version (e.g. plantuml.1.2019.0.jar), `gradle asciidoc` works as expected.

**Comment by codecholeric** [comment]
Thanks for reporting this!! Funny, I was really pondering if I should even publish this plugin since it seemed so rudimentary, but now I immediately get some open issues \*g*.
Ah, I see, I thought that would be the newest published PlantUML version (sorting on Maven Central), even though it was quite old, while actually they changed their versioning scheme. I'll try to upgrade to a current version and see if any more issues arise. (otherwise I could make it a compileOnly dependency and let people plug in a version, but then it's kind of hard to figure out which versions are compatible).

**Comment by codecholeric** [comment]
Can you check if version 1.2.0 fixes your problem?

**Comment by lairdchris** [comment]
> Can you check if version 1.2.0 fixes your problem?

It's working now, thanks :+1:
